### ISSUE TITLE
Redesign of Contact Us Page

### ISSUE THREAD

**Issue by umangkumarr** [umangkumarr/TnpCell-NITD#2]
@aerraj
Revise the Contact Us webpage of website in accordance with the specifications discussed during the meeting.

**Comment by aerraj** [comment]
The redesign of contact us page is completed and this is how the new contact us page looks.
![Screenshot 2023-02-27 173648](https://user-images.githubusercontent.com/61013804/221560224-ba9baff4-2365-4de2-b4ec-16f2d700e4df.png)
![contact](https://user-images.githubusercontent.com/61013804/221560861-530e50a9-165b-43b0-b49c-ea9d3f7eca02.png)
![Screenshot 2023-02-27 173810](https://user-images.githubusercontent.com/61013804/221560378-3f52fc78-a1f2-4d7e-9b7c-a7b4ea6fb3bc.png)
![footer](https://user-images.githubusercontent.com/61013804/221561174-05c44883-786a-44f9-8633-7fdf9acdfaee.png)
